[package]
name = "gitlab_auto_merge"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reqwest = "0.11.4"
serde_json = "1.0.66"
gitlab = "=0.1401.0"
clap = "3.0.0-beta.4"
