[package]
name = "gitlab_auto_merge"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = "1.0.127"
gitlab = "=0.1401.0"
clap = "3.0.0-beta.4"
lazy_static = "1.4.0"
url = "2.2.2"